version: '3'
services:
  # ci:
  #   build: ./ci
  #   volumes:
  #     - ./assets:/assets
  s3:
    build: ./s3
    volumes:
      - "./assets:/assets"
      - "./s3/nginx.config:/etc/nginx/conf.d/default.conf"
  proxy:
    build: ./proxy
    volumes:
      - "./proxy/nginx.config:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
